### ISSUE TITLE
Solution to make this work in Monterey 12.3+

### ISSUE THREAD

**Issue by uandco** [vin047/MacPro41-PowerProfile#1]
Hi there,

No an issue, more a solution, but I thought I'd share it here as it took me a while to get turbo multipliers working on a X5675!

See my write-up here:
https://www.tonymacx86.com/threads/x58-xeon-x5675-needs-speedstep-off-going-from-12-2-to-12-3.322842/#post-2367454

HTH

**Comment by vin047** [comment]
I moved away from hackintoshs (too much trouble), but i'm sure this will be helpful for others 🙂
